image: alpine/edge
packages:
    - git
    - curl
    - python3
sources:
    - https://git.sr.ht/~gpanders/acciobook
secrets:
    - 78f39fb6-1185-492f-9c21-f755e10b5e5d
    - 4039c3d1-35f1-4378-b015-8a9c98b4a0cf
    - 555df4e1-b3c6-49dc-bd4e-b02f8ed0fff3
environment:
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
triggers:
    - action: email
      condition: failure
      to: Gregory Anders <pub@gpanders.com>
tasks:
    - mirror: |
        cd acciobook
        git push --force --mirror git@github.com:gpanders/acciobook
    - build: |
        cd acciobook
        tag=$(git describe --exact-match 2>/dev/null || true)
        if [ -z "$tag" ]; then
            echo "Current commit is not a tag; not building anything"
        else
            export SRHT_TOKEN=$(cat ~/.srht-token)
            . ~/.pypi-credentials
            ./scripts/build.sh "$tag"
        fi
